"""Make user_id nullable for guest checkout

Revision ID: 9435e7d71a67
Revises: 5aaa5b441d19
Create Date: 2026-01-30 22:09:58.513623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9435e7d71a67'
down_revision = '5aaa5b441d19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
